# Site settings
title: "Welcome to H3's blog"
email: "heroh396@gmail.com"
description: "This blog propose useful post from my knowledge."
baseurl: ""
url: "http://heroh396.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
permalink: pretty

gems:
 - jekyll-redirect-from
 - jekyll-redirect-to
