# Site settings
title: "Welcome to the blog"
email: "hhhung96@gmail.com"
description: "This blog propose useful post from my knowledge."
baseurl: ""
url: "http://uetvn.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
permalink: pretty

gems:
 - jekyll-redirect-from
 - jekyll-redirect-to
